/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ConceptsRouteImport } from './routes/concepts'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as ConceptsSlugRouteImport } from './routes/concepts.$slug'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsRoute = ConceptsRouteImport.update({
  id: '/concepts',
  path: '/concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsSlugRoute = ConceptsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ConceptsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/concepts': typeof ConceptsRouteWithChildren
  '/timeline': typeof TimelineRoute
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/concepts': typeof ConceptsRouteWithChildren
  '/timeline': typeof TimelineRoute
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRoute
  '/concepts': typeof ConceptsRouteWithChildren
  '/timeline': typeof TimelineRoute
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/events/$slug': typeof EventsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/companies'
    | '/concepts'
    | '/timeline'
    | '/concepts/$slug'
    | '/events/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies'
    | '/concepts'
    | '/timeline'
    | '/concepts/$slug'
    | '/events/$slug'
  id:
    | '__root__'
    | '/'
    | '/companies'
    | '/concepts'
    | '/timeline'
    | '/concepts/$slug'
    | '/events/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRoute
  ConceptsRoute: typeof ConceptsRouteWithChildren
  TimelineRoute: typeof TimelineRoute
  EventsSlugRoute: typeof EventsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts': {
      id: '/concepts'
      path: '/concepts'
      fullPath: '/concepts'
      preLoaderRoute: typeof ConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/$slug': {
      id: '/concepts/$slug'
      path: '/$slug'
      fullPath: '/concepts/$slug'
      preLoaderRoute: typeof ConceptsSlugRouteImport
      parentRoute: typeof ConceptsRoute
    }
  }
}

interface ConceptsRouteChildren {
  ConceptsSlugRoute: typeof ConceptsSlugRoute
}

const ConceptsRouteChildren: ConceptsRouteChildren = {
  ConceptsSlugRoute: ConceptsSlugRoute,
}

const ConceptsRouteWithChildren = ConceptsRoute._addFileChildren(
  ConceptsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRoute,
  ConceptsRoute: ConceptsRouteWithChildren,
  TimelineRoute: TimelineRoute,
  EventsSlugRoute: EventsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
